# Generated by Django 6.1.1 on 2026-09-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submission_files/'),
        ),
    ]
